ltb-project/white-pages

htdocs/vendor/datatables/i18n/en.json, htdocs/vendor/datatables/i18n/fr.json, htdocs/vendor/datatables/i18n/it.json, lang/en.inc.php, lang/fr.inc.php, lang/it.inc.php, templates/footer.tpl
Following #28 : add a translation token for "All" option in Datatables pager
Also I have made the changes for #27
=> Directory view translations

conf/config.inc.php, htdocs/display.php
Implementing author suggestion addressing ltb-project/white-pages#51
Somewhat related to ltb-project/white-pages#45
=> fix(display): introducing optional `$ldap_user_regex`

conf/config.inc.php, htdocs/css/white-pages.css, htdocs/index.php, templates/footer.tpl
The footer can be disabled by configuration
=> Set version in code and display it in footer (ltb-project#50)

conf/config.inc.php, htdocs/directory.php, templates/directory.tpl
Other solution than https://github.com/ltb-project/white-pages/pull/56
=> Add buttons in directory page to switch between users and groups (ltb-project#55)

conf/config.inc.php, htdocs/gallery.php
A new parameter is created: `$gallery_user_filter`
=> Possibility to set a specific filter for gallery (ltb-project#54)

conf/config.inc.php, htdocs/index.php, templates/menu.tpl
We can now set which page is displayed by default
=> Configure default page

conf/config.inc.php, htdocs/display.php, lang/en.inc.php, lang/fr.inc.php, lang/it.inc.php, templates/display.tpl
New configuration parameter: `$display_edit_link`
=> Option to add an edit link in entry display page (ltb-project#49)

conf/config.inc.php, htdocs/advancedsearch.php, lib/ldap.inc.php, templates/advancedsearch.tpl, templates/search_displayer.tpl, templates/value_displayer.tpl
This new type can be used to build a list of values from an LDAP query, that will be displayed as a select input in advanced search form.
=> Provide a new type (list)

htdocs/gallery.php, templates/listing_table.tpl
=> Add gallery by group

htdocs/index.php
=> Disable error reporting if debug is false

conf/config.inc.php, htdocs/index.php, lang/en.inc.php, lang/fr.inc.php, lang/it.inc.php, lib/filesize.inc.php, lib/smarty.inc.php, templates/search_displayer.tpl, templates/value_displayer.tpl
=> New type "bytes"

conf/config.inc.php, htdocs/advancedsearch.php, htdocs/directory.php, htdocs/display.php, htdocs/gallery.php, htdocs/index.php, htdocs/photo.php, htdocs/search.php, lib/ldap.inc.php, lib/smarty.inc.php, templates/value_displayer.tpl
New option `$ldap_network_timeout`
Resolves #76
=> Add ldap_network_timeout option

conf/config.inc.php
See https://github.com/ltb-project/service-desk/pull/17
=> Allow the Smarty path to be set in conf.inc.local.php

conf/config.inc.php, htdocs/index.php, templates/footer.tpl
Work from @pcurie and @faust64
=> Patch datepicker lang

packaging/docker/Dockerfile, packaging/kubernetes/deploy.yaml
mostly as a FYI
building & testing changes quickly in k8s.
=> feat(docker): sample docker image & kubernetes deployment

htdocs/display.php, htdocs/index.php
Getting rid of some warnings, as seen in #103
=> Fix undefined warnings

docs/advancedsearch.rst, docs/attributes.rst, docs/conf.py, docs/csvexport.rst, docs/directorymenu.rst, docs/entriesdisplay.rst, docs/fulldisplay.rst, docs/gallerymenu.rst, docs/index.rst, docs/ldap-parameters.rst, docs/photos.rst, docs/presentation.rst, docs/vcardexport.rst
=> Fixes on online doc

conf/config.inc.php, docs/general-parameters.rst, htdocs/index.php, packaging/debian/replace_cache_dirs, packaging/debian/rules, packaging/debian/white-pages.dirs, packaging/rpm/SPECS/white-pages.spec
References #93 
Configuration of cache directories
=> Manage cache dirs

docs/installation.rst, docs/ldap-parameters.rst, htdocs/display.php
Fix for issue #124 
Object detection is done with `$ldap_user_filter` and `ldap_group_filter`
=> Group rendering

conf/config.inc.php, docs/general-parameters.rst
=> Multi tenancy

conf/config.inc.php, docs/attributes.rst, htdocs/index.php, templates/value_displayer.tpl
=> Configure values for DN links

templates/value_displayer.tpl
=> Fix HTML escaping in dn_link

conf/config.inc.php, docs/general-parameters.rst, htdocs/index.php
=> Customized templates

packaging/README, packaging/docker/Dockerfile, packaging/docker/Dockerfile.alpine, packaging/docker/apache2.alpine/white-pages.conf, packaging/docker/entrypoint.sh, packaging/docker/install
Use improved Docker images, with the work done in SSP and SD
=> Upgrade Docker packaging files

conf/config.inc.php, docs/general-parameters.rst, htdocs/index.php, templates/header.tpl
Allow to configure your own favicon
=> Configuration for favicon

htdocs/api/search_dn.php, htdocs/js/update.js, templates/value_editor.tpl
Now we display an error message if any error on server side, and a warning when size limit is reached
Related to #169
=> Manage error and warning messages in dn_list editor

conf/config.inc.php, docs/attributes.rst, htdocs/api/search_dn.php, htdocs/index.php, htdocs/js/update.js, templates/value_editor.tpl
Create configuration parameters for dn_link editor
=> New configuration settings for dn_link component
